CASE_DEFINITION = {
    "slug": "cemetery-gate",
    "title": "The Cemetery Gate",
    "summary": "The cemetery's north gate keeps turning up wet, unlocked, and facing the wrong way by morning.",
    "starting_location_slug": "cemetery",
    "outcome_text": "June was hiding a late-night shortcut for the bus depot clerk. The hinge was cleaned with river water, for reasons nobody explains.",
    "requirements": {},
    "completion_effects": {
        "weirdness_tolerance": 1,
        "cemetery_trust": 1,
        "bus_depot_trust": 1,
        "skeptical": -1,
    },
    "steps": [
        {
            "action": "start",
            "label": "Ask June about the wet gate",
            "location_slug": "cemetery",
            "location_name": "Cemetery",
            "clue": "wet-lock",
            "next_step": 1,
        },
        {
            "action": "library",
            "label": "Compare the old burial map",
            "location_slug": "library",
            "location_name": "Library",
            "clue": "north-row-map",
            "next_step": 2,
        },
        {
            "action": "depot",
            "label": "Check the late bus schedule",
            "location_slug": "bus-depot",
            "location_name": "Bus Depot",
            "clue": "folded-ticket",
            "next_step": 3,
        },
        {
            "action": "finish",
            "label": "Close the cemetery gate case",
            "location_slug": "cemetery",
            "location_name": "Cemetery",
            "clue": "cleaned-hinge",
            "next_step": 4,
        },
    ],
    "clues": [
        ("wet-lock", "A wet lock", "The north gate lock is damp inside, though the rest of the iron is dry.", 1),
        ("north-row-map", "The north row map", "An old library map shows a service path from the cemetery toward the depot.", 2),
        ("folded-ticket", "A folded bus ticket", "The ticket is punched after midnight and tucked into the wrong schedule slot.", 3),
        ("cleaned-hinge", "A cleaned hinge", "The hinge was scrubbed with river water and a strip of diner towel.", 4),
    ],
}
